// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// MonitorWrapper is an autogenerated mock type for the MonitorWrapper type
type MonitorWrapper struct {
	mock.Mock
}

// Execute provides a mock function with given fields: path, handler
func (_m *MonitorWrapper) Execute(path string, handler http.Handler) http.Handler {
	ret := _m.Called(path, handler)

	var r0 http.Handler
	if rf, ok := ret.Get(0).(func(string, http.Handler) http.Handler); ok {
		r0 = rf(path, handler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Handler)
		}
	}

	return r0
}
